---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: cluster
    app.kubernetes.io/version: "1.0.0"
  name: kubequery

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubequery-sa
  namespace: kubequery

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubequery-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubequery-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: kubequery-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubequery-sa
  namespace: kubequery

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubequery-config
  namespace: kubequery
data:
  osquery.flags: |
    --extension=/usr/bin/kubequery
  osquery.conf: |
    {
      "schedule": {
      },
      "options":{
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubequery
  name: kubequery
  namespace: kubequery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubequery
  template:
    metadata:
      labels:
        app: kubequery
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: kubequery-sa
      containers:
        - name: kubequery
          image: uptycs/kubequery:latest
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
          - name: config
            mountPath: /etc/osquery
      volumes:
      - name: config
        configMap:
          name: kubequery-config
